services:
  flask:
    image: ahafez2k/flux_server
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-db:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  postgres-db: {} 



   